### ISSUE TITLE
New Contact Page Layout

### ISSUE THREAD

**Issue by lbl-knts** [5knots/Custom-CSS-Drupal#1]
The site available under `/civicrm/contact/add?reset=1&ct=Individual` looks different (and worse) from CiviCRM with Drupal 7.
![Bildschirmfoto 2022-04-21 um 13 15 11](https://user-images.githubusercontent.com/48119506/164447077-5e3552d0-2c8a-4d96-bcb5-ddd1e4983bb5.png)

**Comment by jennirocket** [comment]
Done
