### ISSUE TITLE
header in white on background light grey

### ISSUE THREAD

**Issue by lbl-knts** [5knots/Custom-CSS-Drupal#11]
is almost not readable, to see at "activities" --> "view". But this appears more general, on many screens. Would be nice to find a more general css class.
![Bildschirmfoto 2022-05-09 um 09 15 53](https://user-images.githubusercontent.com/48119506/167359347-2a91e380-7f5b-4602-93c6-6e321d65c29d.png)

**Comment by jennirocket** [comment]
![Screenshot from 2022-05-28 12-26-03](https://user-images.githubusercontent.com/72915121/170821371-6dc5982d-f32c-4fed-a7eb-3ebcac5f8734.png)
 Already fixed
