### ISSUE TITLE
alignment of new profile is poor

### ISSUE THREAD

**Issue by lbl-knts** [5knots/Custom-CSS-Drupal#13]
see /civicrm/contribute/transact?reset=1&id=1 with new id
![Bildschirmfoto 2022-05-09 um 09 40 26](https://user-images.githubusercontent.com/48119506/167363099-34e4b01f-1f88-4056-9142-a4c0ce32a3a0.png)

**Comment by lbl-knts** [comment]
.. .and ongoing, with adding fields in the profile, the layout is really bad
![Bildschirmfoto 2022-05-09 um 09 42 33](https://user-images.githubusercontent.com/48119506/167363463-5a1e3235-f463-4e0b-9d88-07a9439ba817.png)
.

**Comment by jennirocket** [comment]
Fixed
