### ISSUE TITLE
poor layout price set fields

### ISSUE THREAD

**Issue by lbl-knts** [5knots/Custom-CSS-Drupal#14]
with editing a price set field, the alignment is poor. Also the header is white on light grey.
![Bildschirmfoto 2022-05-09 um 09 48 04](https://user-images.githubusercontent.com/48119506/167364422-ecc224b0-b405-4b29-a687-41ed65719cce.png)
avaliable here (with valid id) /civicrm/admin/price/field?reset=1&action=browse&sid=3

**Comment by jennirocket** [comment]
Fixed
