### ISSUE TITLE
poor layout edit a contribution page

### ISSUE THREAD

**Issue by lbl-knts** [5knots/Custom-CSS-Drupal#15]
see screenshot: civicrm/admin/contribute/membership?reset=1&action=update&id=1 with valid id
![Bildschirmfoto 2022-05-09 um 09 51 25](https://user-images.githubusercontent.com/48119506/167365115-faca9099-fa00-4bb1-bfe4-346d87f69055.png)

**Comment by lbl-knts** [comment]
on the same site, the header cover fields with active "Abschnitt 'Zahlungsbetrag' aktiviert"
![Bildschirmfoto 2022-05-09 um 10 03 55](https://user-images.githubusercontent.com/48119506/167366857-99e487a5-ece8-4382-93fc-227ed52161c3.png)

**Comment by jennirocket** [comment]
Fixed
