### ISSUE TITLE
groups with children and parents

### ISSUE THREAD

**Issue by lbl-knts** [5knots/Custom-CSS-Drupal#2]
hierarchical groups have an triangle in front of the group. If you open the parent group, the triangle jumps a bit. Furthermore, if the parent group ist open, it is not clear, wether "next group" belongs to the parent group or is simply the next normal group. Example in the screenshots with "Administrative Gruppen".
![Bildschirmfoto 2022-04-21 um 13 35 12](https://user-images.githubusercontent.com/48119506/164449752-c4c39880-dd94-41a2-b3ab-856fc036accf.png)
![Bildschirmfoto 2022-04-21 um 13 35 20](https://user-images.githubusercontent.com/48119506/164449759-56a68764-4a36-403b-8d85-51dcc0bb96aa.png)
.

**Comment by jennirocket** [comment]
Done
