### ISSUE TITLE
wordwrap

### ISSUE THREAD

**Issue by AnkeKnoten** [5knots/Custom-CSS-Drupal#22]
/civicrm/group/add?reset=1
![Bildschirmfoto vom 2022-08-30 11-52-13](https://user-images.githubusercontent.com/108866426/187425934-3a43e98e-8a7b-4d86-ab04-6fbec68a34a2.png)

**Comment by knottheory** [comment]
Text input fields don't line up. Table elements don't wrap correctly

**Comment by AnkeKnoten** [comment]
![Bildschirmfoto vom 2022-12-06 10-48-32](https://user-images.githubusercontent.com/108866426/205878289-0bfb9bfa-f94e-41c5-bee1-7c16d86b03e6.png)
