### ISSUE TITLE
hidden fields

### ISSUE THREAD

**Issue by AnkeKnoten** [5knots/Custom-CSS-Drupal#23]
/civicrm/admin/setting/date?reset=1

![Bildschirmfoto vom 2022-10-10 13-37-29](https://user-images.githubusercontent.com/108866426/194859138-a4a87364-f9e4-4ee9-bb11-933266a71983.png)

**Comment by knottheory** [comment]
Issue fixed in dev needs review before merging

**Comment by AnkeKnoten** [comment]
![Bildschirmfoto vom 2022-10-10 13-37-29](https://user-images.githubusercontent.com/108866426/205878926-1dbd0904-bb7f-408d-87ad-84a86c872414.png)

It looks like before (-->lebenimeinklangmitdernatur.de)
