### ISSUE TITLE
fields not flush

### ISSUE THREAD

**Issue by AnkeKnoten** [5knots/Custom-CSS-Drupal#24]
civicrm/contact/add?reset=1 ct=Individual

![civicrm_contact_add?reset=1 ct=Individual](https://user-images.githubusercontent.com/108866426/195079708-2048040a-26f4-44f8-8784-812895e68b2a.png)

**Comment by knottheory** [comment]
Text area has position: relative; left: -18pxM
![Screenshot from 2022-11-04 16-03-43](https://user-images.githubusercontent.com/112637109/200007900-e2f4e38d-2d01-4bc7-9d07-316369e0065d.png)
![Screenshot from 2022-11-04 16-08-24](https://user-images.githubusercontent.com/112637109/200008819-baf1a0ea-e156-4918-9d13-f3da8a8c635f.png)

**Comment by AnkeKnoten** [comment]
I
![civicrm_contact_add?reset=1 ct=Individual](https://user-images.githubusercontent.com/108866426/205879866-6c878c8a-44dd-4c92-93fb-7dc66d84c3d1.png)

-->lebenimeinklagmitdernatur.de
