### ISSUE TITLE
add new activity layout

### ISSUE THREAD

**Issue by lbl-knts** [5knots/Custom-CSS-Drupal#3]
with adding a new activity to a contact, the layout is bad.

/add?action=add&reset=1&cid=6&selectedChild=activity&atype=70
![Bildschirmfoto 2022-04-21 um 13 45 41](https://user-images.githubusercontent.com/48119506/164451533-05fc3fc8-4a44-4fa3-ae46-7043c5ecf6d5.png)
![Bildschirmfoto 2022-04-21 um 13 45 49](https://user-images.githubusercontent.com/48119506/164451538-89fdaa15-e27e-44b8-a85a-586c26e38401.png)
![Bildschirmfoto 2022-04-21 um 13 45 56](https://user-images.githubusercontent.com/48119506/164451549-c52b17e4-762b-41c0-aa18-f86fceb0bd4e.png)

**Comment by jennirocket** [comment]
Already done
