### ISSUE TITLE
Centralize general CSS fixes for shoreditch

### ISSUE THREAD

**Issue by Matt5K** [5knots/Custom-CSS-Drupal#6]
To centralize general shoreditch CSS fixes the @import feature of CSS could be used (https://www.w3schools.com/cssref/pr_import_rule.asp). Via @import it is possible to load CSS rules into a CSS file from a web ressource.

Example:

`@import url("https://5knoten.de/assets/custom_shoreditch.css"); /* Using a url */`

Todo:

- bundle all general CSS fixes in one file in a github repository
- make this repository public
- create a public available URL for the general CSS fixes (github may not allow file hosting so use another source for the import)
--- e.g. "https://5knoten.de/assets/custom_shoreditch.css"
- check if the servers where CiviCRM instances run do allow loading resources from other domains
--- if not change "allow origin" settings and add URL for general CSS fixes

For manual CSS updates
- run git checkout at the public URL

To auto update CSS changes
- create a PHP script that updates the file via git if called (like this -> https://gist.github.com/andre3k1/97dd45d0c8eba443789b)
--- alter this script - change paths, accounts, repository
- create a github hook to push a notice to this PHP file
- update all customized CSS files in projects CSS fixes for shoreditch 
--- add `@import url("https://5knoten.de/assets/custom_shoreditch.css"); ` at the first line 
--- remove any general CCS rules

**Comment by jennirocket** [comment]
Done
