### ISSUE TITLE
poor adress fields 

### ISSUE THREAD

**Issue by lbl-knts** [5knots/Custom-CSS-Drupal#8]
The help icons aren't in place, please see screenshot. path is [domain]/civicrm/contact/add?reset=1&ct=Individual
![Bildschirmfoto 2022-05-09 um 08 39 24](https://user-images.githubusercontent.com/48119506/167354125-09047386-e3c5-40d8-96e5-fb6430cb2d56.png)
.

**Comment by jennirocket** [comment]
Fixed
