### ISSUE TITLE
new membership in new tab

### ISSUE THREAD

**Issue by lbl-knts** [5knots/Custom-CSS-Drupal#9]
left alignment isn't in a line, see screenshot, URL with valid contact id = [domain]/civicrm/contact/view/membership?reset=1&action=add&cid=44&context=membershi
![Bildschirmfoto 2022-05-09 um 08 43 31](https://user-images.githubusercontent.com/48119506/167354780-5d2b704b-c4fe-4b75-b9e6-e84b94b54001.png)
p

**Comment by lbl-knts** [comment]
opened "new membership" in a popup looks even more poor and even more unsorted
![Bildschirmfoto 2022-05-09 um 08 46 26](https://user-images.githubusercontent.com/48119506/167355013-6934212d-3e0d-41a6-8890-44805e1bb584.png)
.

**Comment by jennirocket** [comment]
Done, only seemed to be the case for the Oblaten Instance
